// Generated by Bisonc++ V5.02.00 on Sat, 23 Feb 2019 00:02:09 +0100

// $insert class.ih
#include "Parser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token__ is _UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token__ in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on _error_
// which is applied. In this _error_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
// Last element:    {set to d_token__,    action to perform}
//      }

// When the --thread-safe option is specified, all static data are defined as
// const. If --thread-safe is not provided, the state-tables are not defined
// as const, since the lookup() function below will modify them


namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum ReservedTokens
    {
        PARSE_ACCEPT     = 0,   // `ACCEPT' TRANSITION
        _UNDETERMINED_   = -2,
        _EOF_            = -1,
        _error_          = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            int d_type;
            int d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
            size_t d_errorState;    // used with Error states
        };
    };

    // $insert staticdata
    
    enum                        // size to expand the state-stack with when
    {                           // full
        STACK_EXPANSION__ = 10
    };

// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {292, 1}, // 1: start ->  program
     {293, 3}, // 2: program ->  header declarations body
     {294, 2}, // 3: header (PROGRAM) ->  PROGRAM IDENTIFIER
     {295, 0}, // 4: declarations ->  <empty>
     {295, 2}, // 5: declarations ->  declaration declarations
     {297, 3}, // 6: declaration (IDENTIFIER) ->  type IDENTIFIER SEMICOLON
     {298, 1}, // 7: type (NATURAL) ->  NATURAL
     {298, 1}, // 8: type (BOOLEAN) ->  BOOLEAN
     {296, 3}, // 9: body (BEGIN) ->  BEGIN expressions END
     {299, 0}, // 10: expressions ->  <empty>
     {299, 2}, // 11: expressions ->  expression expressions
     {300, 1}, // 12: expression ->  read
     {300, 1}, // 13: expression ->  write
     {300, 1}, // 14: expression ->  assignment
     {300, 1}, // 15: expression ->  while_loop
     {300, 3}, // 16: expression ->  if_statement #0001 skip
     {307, 0}, // 17: #0001 ->  <empty>
     {301, 5}, // 18: read (READ) ->  READ LEFT_PARENTHESIS IDENTIFIER RIGHT_PARENTHESIS SEMICOLON
     {302, 5}, // 19: write (WRITE) ->  WRITE LEFT_PARENTHESIS expr RIGHT_PARENTHESIS SEMICOLON
     {303, 4}, // 20: assignment (IDENTIFIER) ->  IDENTIFIER ASSIGN expr SEMICOLON
     {304, 5}, // 21: while_loop (WHILE) ->  WHILE expr DO expressions DONE
     {305, 4}, // 22: if_statement (IF) ->  IF expr THEN if_second_half
     {309, 2}, // 23: if_second_half (ENDIF) ->  expressions ENDIF
     {309, 4}, // 24: if_second_half (ELSE) ->  expressions ELSE expressions ENDIF
     {309, 5}, // 25: if_second_half (ELSEIF) ->  expressions ELSEIF expr THEN if_second_half
     {308, 1}, // 26: expr (TRUE) ->  TRUE
     {308, 1}, // 27: expr (FALSE) ->  FALSE
     {308, 1}, // 28: expr (IDENTIFIER) ->  IDENTIFIER
     {308, 1}, // 29: expr (NATURAL_LITERAL) ->  NATURAL_LITERAL
     {308, 3}, // 30: expr (EQUAL) ->  expr EQUAL expr
     {308, 3}, // 31: expr (LEFT_PARENTHESIS) ->  LEFT_PARENTHESIS expr RIGHT_PARENTHESIS
     {308, 2}, // 32: expr (NOT) ->  NOT expr
     {308, 3}, // 33: expr (AND) ->  expr AND expr
     {308, 3}, // 34: expr (OR) ->  expr OR expr
     {308, 3}, // 35: expr (LESS_THAN) ->  expr LESS_THAN expr
     {308, 3}, // 36: expr (GREATER_THAN) ->  expr GREATER_THAN expr
     {308, 3}, // 37: expr (PLUS) ->  expr PLUS expr
     {308, 3}, // 38: expr (MINUS) ->  expr MINUS expr
     {308, 3}, // 39: expr (MULTIPLY) ->  expr MULTIPLY expr
     {308, 3}, // 40: expr (DIV) ->  expr DIV expr
     {308, 3}, // 41: expr (MOD) ->  expr MOD expr
     {306, 2}, // 42: skip (SKIP) ->  SKIP SEMICOLON
     {310, 1}, // 43: start_$ ->  start
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { REQ_TOKEN}, { 5} },           
    { {       292}, { 1} }, // start  
    { {       293}, { 2} }, // program
    { {       294}, { 3} }, // header 
    { {       257}, { 4} }, // PROGRAM
    { {         0}, { 0} },           
};

SR__ s_1[] =
{
    { { REQ_TOKEN}, {            2} }, 
    { {     _EOF_}, { PARSE_ACCEPT} }, 
    { {         0}, {            0} }, 
};

SR__ s_2[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -1} }, 
};

SR__ s_3[] =
{
    { { REQ_DEF}, {  6} },                
    { {     295}, {  5} }, // declarations
    { {     297}, {  6} }, // declaration 
    { {     298}, {  7} }, // type        
    { {     260}, {  8} }, // NATURAL     
    { {     261}, {  9} }, // BOOLEAN     
    { {       0}, { -4} },                
};

SR__ s_4[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       276}, { 10} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR__ s_5[] =
{
    { { REQ_TOKEN}, {  3} },         
    { {       296}, { 11} }, // body 
    { {       258}, { 12} }, // BEGIN
    { {         0}, {  0} },         
};

SR__ s_6[] =
{
    { { REQ_DEF}, {  6} },                
    { {     295}, { 13} }, // declarations
    { {     297}, {  6} }, // declaration 
    { {     298}, {  7} }, // type        
    { {     260}, {  8} }, // NATURAL     
    { {     261}, {  9} }, // BOOLEAN     
    { {       0}, { -4} },                
};

SR__ s_7[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       276}, { 14} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR__ s_8[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -7} }, 
};

SR__ s_9[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -8} }, 
};

SR__ s_10[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -3} }, 
};

SR__ s_11[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -2} }, 
};

SR__ s_12[] =
{
    { { REQ_DEF}, {  13} },                
    { {     299}, {  15} }, // expressions 
    { {     300}, {  16} }, // expression  
    { {     301}, {  17} }, // read        
    { {     302}, {  18} }, // write       
    { {     303}, {  19} }, // assignment  
    { {     304}, {  20} }, // while_loop  
    { {     305}, {  21} }, // if_statement
    { {     274}, {  22} }, // READ        
    { {     275}, {  23} }, // WRITE       
    { {     276}, {  24} }, // IDENTIFIER  
    { {     271}, {  25} }, // WHILE       
    { {     266}, {  26} }, // IF          
    { {       0}, { -10} },                
};

SR__ s_13[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -5} }, 
};

SR__ s_14[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       280}, { 27} }, // SEMICOLON
    { {         0}, {  0} },             
};

SR__ s_15[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {       259}, { 28} }, // END
    { {         0}, {  0} },       
};

SR__ s_16[] =
{
    { { REQ_DEF}, {  13} },                
    { {     299}, {  29} }, // expressions 
    { {     300}, {  16} }, // expression  
    { {     301}, {  17} }, // read        
    { {     302}, {  18} }, // write       
    { {     303}, {  19} }, // assignment  
    { {     304}, {  20} }, // while_loop  
    { {     305}, {  21} }, // if_statement
    { {     274}, {  22} }, // READ        
    { {     275}, {  23} }, // WRITE       
    { {     276}, {  24} }, // IDENTIFIER  
    { {     271}, {  25} }, // WHILE       
    { {     266}, {  26} }, // IF          
    { {       0}, { -10} },                
};

SR__ s_17[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -12} }, 
};

SR__ s_18[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -13} }, 
};

SR__ s_19[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -14} }, 
};

SR__ s_20[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -15} }, 
};

SR__ s_21[] =
{
    { { DEF_RED}, {   2} },         
    { {     307}, {  30} }, // #0001
    { {       0}, { -17} },         
};

SR__ s_22[] =
{
    { { REQ_TOKEN}, {  2} },                    
    { {       277}, { 31} }, // LEFT_PARENTHESIS
    { {         0}, {  0} },                    
};

SR__ s_23[] =
{
    { { REQ_TOKEN}, {  2} },                    
    { {       277}, { 32} }, // LEFT_PARENTHESIS
    { {         0}, {  0} },                    
};

SR__ s_24[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       279}, { 33} }, // ASSIGN
    { {         0}, {  0} },          
};

SR__ s_25[] =
{
    { { REQ_TOKEN}, {  8} },                    
    { {       308}, { 34} }, // expr            
    { {       262}, { 35} }, // TRUE            
    { {       263}, { 36} }, // FALSE           
    { {       276}, { 37} }, // IDENTIFIER      
    { {       281}, { 38} }, // NATURAL_LITERAL 
    { {       277}, { 39} }, // LEFT_PARENTHESIS
    { {       264}, { 40} }, // NOT             
    { {         0}, {  0} },                    
};

SR__ s_26[] =
{
    { { REQ_TOKEN}, {  8} },                    
    { {       308}, { 41} }, // expr            
    { {       262}, { 35} }, // TRUE            
    { {       263}, { 36} }, // FALSE           
    { {       276}, { 37} }, // IDENTIFIER      
    { {       281}, { 38} }, // NATURAL_LITERAL 
    { {       277}, { 39} }, // LEFT_PARENTHESIS
    { {       264}, { 40} }, // NOT             
    { {         0}, {  0} },                    
};

SR__ s_27[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -6} }, 
};

SR__ s_28[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -9} }, 
};

SR__ s_29[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -11} }, 
};

SR__ s_30[] =
{
    { { REQ_TOKEN}, {  3} },        
    { {       306}, { 42} }, // skip
    { {       265}, { 43} }, // SKIP
    { {         0}, {  0} },        
};

SR__ s_31[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       276}, { 44} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR__ s_32[] =
{
    { { REQ_TOKEN}, {  8} },                    
    { {       308}, { 45} }, // expr            
    { {       262}, { 35} }, // TRUE            
    { {       263}, { 36} }, // FALSE           
    { {       276}, { 37} }, // IDENTIFIER      
    { {       281}, { 38} }, // NATURAL_LITERAL 
    { {       277}, { 39} }, // LEFT_PARENTHESIS
    { {       264}, { 40} }, // NOT             
    { {         0}, {  0} },                    
};

SR__ s_33[] =
{
    { { REQ_TOKEN}, {  8} },                    
    { {       308}, { 46} }, // expr            
    { {       262}, { 35} }, // TRUE            
    { {       263}, { 36} }, // FALSE           
    { {       276}, { 37} }, // IDENTIFIER      
    { {       281}, { 38} }, // NATURAL_LITERAL 
    { {       277}, { 39} }, // LEFT_PARENTHESIS
    { {       264}, { 40} }, // NOT             
    { {         0}, {  0} },                    
};

SR__ s_34[] =
{
    { { REQ_TOKEN}, { 12} },                
    { {       272}, { 47} }, // DO          
    { {       284}, { 48} }, // EQUAL       
    { {       282}, { 49} }, // AND         
    { {       283}, { 50} }, // OR          
    { {       285}, { 51} }, // LESS_THAN   
    { {       286}, { 52} }, // GREATER_THAN
    { {       287}, { 53} }, // PLUS        
    { {       288}, { 54} }, // MINUS       
    { {       289}, { 55} }, // MULTIPLY    
    { {       290}, { 56} }, // DIV         
    { {       291}, { 57} }, // MOD         
    { {         0}, {  0} },                
};

SR__ s_35[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -26} }, 
};

SR__ s_36[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -27} }, 
};

SR__ s_37[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -28} }, 
};

SR__ s_38[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -29} }, 
};

SR__ s_39[] =
{
    { { REQ_TOKEN}, {  8} },                    
    { {       308}, { 58} }, // expr            
    { {       262}, { 35} }, // TRUE            
    { {       263}, { 36} }, // FALSE           
    { {       276}, { 37} }, // IDENTIFIER      
    { {       281}, { 38} }, // NATURAL_LITERAL 
    { {       277}, { 39} }, // LEFT_PARENTHESIS
    { {       264}, { 40} }, // NOT             
    { {         0}, {  0} },                    
};

SR__ s_40[] =
{
    { { REQ_TOKEN}, {  8} },                    
    { {       308}, { 59} }, // expr            
    { {       262}, { 35} }, // TRUE            
    { {       263}, { 36} }, // FALSE           
    { {       276}, { 37} }, // IDENTIFIER      
    { {       281}, { 38} }, // NATURAL_LITERAL 
    { {       277}, { 39} }, // LEFT_PARENTHESIS
    { {       264}, { 40} }, // NOT             
    { {         0}, {  0} },                    
};

SR__ s_41[] =
{
    { { REQ_TOKEN}, { 12} },                
    { {       267}, { 60} }, // THEN        
    { {       284}, { 48} }, // EQUAL       
    { {       282}, { 49} }, // AND         
    { {       283}, { 50} }, // OR          
    { {       285}, { 51} }, // LESS_THAN   
    { {       286}, { 52} }, // GREATER_THAN
    { {       287}, { 53} }, // PLUS        
    { {       288}, { 54} }, // MINUS       
    { {       289}, { 55} }, // MULTIPLY    
    { {       290}, { 56} }, // DIV         
    { {       291}, { 57} }, // MOD         
    { {         0}, {  0} },                
};

SR__ s_42[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -16} }, 
};

SR__ s_43[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       280}, { 61} }, // SEMICOLON
    { {         0}, {  0} },             
};

SR__ s_44[] =
{
    { { REQ_TOKEN}, {  2} },                     
    { {       278}, { 62} }, // RIGHT_PARENTHESIS
    { {         0}, {  0} },                     
};

SR__ s_45[] =
{
    { { REQ_TOKEN}, { 12} },                     
    { {       278}, { 63} }, // RIGHT_PARENTHESIS
    { {       284}, { 48} }, // EQUAL            
    { {       282}, { 49} }, // AND              
    { {       283}, { 50} }, // OR               
    { {       285}, { 51} }, // LESS_THAN        
    { {       286}, { 52} }, // GREATER_THAN     
    { {       287}, { 53} }, // PLUS             
    { {       288}, { 54} }, // MINUS            
    { {       289}, { 55} }, // MULTIPLY         
    { {       290}, { 56} }, // DIV              
    { {       291}, { 57} }, // MOD              
    { {         0}, {  0} },                     
};

SR__ s_46[] =
{
    { { REQ_TOKEN}, { 12} },                
    { {       280}, { 64} }, // SEMICOLON   
    { {       284}, { 48} }, // EQUAL       
    { {       282}, { 49} }, // AND         
    { {       283}, { 50} }, // OR          
    { {       285}, { 51} }, // LESS_THAN   
    { {       286}, { 52} }, // GREATER_THAN
    { {       287}, { 53} }, // PLUS        
    { {       288}, { 54} }, // MINUS       
    { {       289}, { 55} }, // MULTIPLY    
    { {       290}, { 56} }, // DIV         
    { {       291}, { 57} }, // MOD         
    { {         0}, {  0} },                
};

SR__ s_47[] =
{
    { { REQ_DEF}, {  13} },                
    { {     299}, {  65} }, // expressions 
    { {     300}, {  16} }, // expression  
    { {     301}, {  17} }, // read        
    { {     302}, {  18} }, // write       
    { {     303}, {  19} }, // assignment  
    { {     304}, {  20} }, // while_loop  
    { {     305}, {  21} }, // if_statement
    { {     274}, {  22} }, // READ        
    { {     275}, {  23} }, // WRITE       
    { {     276}, {  24} }, // IDENTIFIER  
    { {     271}, {  25} }, // WHILE       
    { {     266}, {  26} }, // IF          
    { {       0}, { -10} },                
};

SR__ s_48[] =
{
    { { REQ_TOKEN}, {  8} },                    
    { {       308}, { 66} }, // expr            
    { {       262}, { 35} }, // TRUE            
    { {       263}, { 36} }, // FALSE           
    { {       276}, { 37} }, // IDENTIFIER      
    { {       281}, { 38} }, // NATURAL_LITERAL 
    { {       277}, { 39} }, // LEFT_PARENTHESIS
    { {       264}, { 40} }, // NOT             
    { {         0}, {  0} },                    
};

SR__ s_49[] =
{
    { { REQ_TOKEN}, {  8} },                    
    { {       308}, { 67} }, // expr            
    { {       262}, { 35} }, // TRUE            
    { {       263}, { 36} }, // FALSE           
    { {       276}, { 37} }, // IDENTIFIER      
    { {       281}, { 38} }, // NATURAL_LITERAL 
    { {       277}, { 39} }, // LEFT_PARENTHESIS
    { {       264}, { 40} }, // NOT             
    { {         0}, {  0} },                    
};

SR__ s_50[] =
{
    { { REQ_TOKEN}, {  8} },                    
    { {       308}, { 68} }, // expr            
    { {       262}, { 35} }, // TRUE            
    { {       263}, { 36} }, // FALSE           
    { {       276}, { 37} }, // IDENTIFIER      
    { {       281}, { 38} }, // NATURAL_LITERAL 
    { {       277}, { 39} }, // LEFT_PARENTHESIS
    { {       264}, { 40} }, // NOT             
    { {         0}, {  0} },                    
};

SR__ s_51[] =
{
    { { REQ_TOKEN}, {  8} },                    
    { {       308}, { 69} }, // expr            
    { {       262}, { 35} }, // TRUE            
    { {       263}, { 36} }, // FALSE           
    { {       276}, { 37} }, // IDENTIFIER      
    { {       281}, { 38} }, // NATURAL_LITERAL 
    { {       277}, { 39} }, // LEFT_PARENTHESIS
    { {       264}, { 40} }, // NOT             
    { {         0}, {  0} },                    
};

SR__ s_52[] =
{
    { { REQ_TOKEN}, {  8} },                    
    { {       308}, { 70} }, // expr            
    { {       262}, { 35} }, // TRUE            
    { {       263}, { 36} }, // FALSE           
    { {       276}, { 37} }, // IDENTIFIER      
    { {       281}, { 38} }, // NATURAL_LITERAL 
    { {       277}, { 39} }, // LEFT_PARENTHESIS
    { {       264}, { 40} }, // NOT             
    { {         0}, {  0} },                    
};

SR__ s_53[] =
{
    { { REQ_TOKEN}, {  8} },                    
    { {       308}, { 71} }, // expr            
    { {       262}, { 35} }, // TRUE            
    { {       263}, { 36} }, // FALSE           
    { {       276}, { 37} }, // IDENTIFIER      
    { {       281}, { 38} }, // NATURAL_LITERAL 
    { {       277}, { 39} }, // LEFT_PARENTHESIS
    { {       264}, { 40} }, // NOT             
    { {         0}, {  0} },                    
};

SR__ s_54[] =
{
    { { REQ_TOKEN}, {  8} },                    
    { {       308}, { 72} }, // expr            
    { {       262}, { 35} }, // TRUE            
    { {       263}, { 36} }, // FALSE           
    { {       276}, { 37} }, // IDENTIFIER      
    { {       281}, { 38} }, // NATURAL_LITERAL 
    { {       277}, { 39} }, // LEFT_PARENTHESIS
    { {       264}, { 40} }, // NOT             
    { {         0}, {  0} },                    
};

SR__ s_55[] =
{
    { { REQ_TOKEN}, {  8} },                    
    { {       308}, { 73} }, // expr            
    { {       262}, { 35} }, // TRUE            
    { {       263}, { 36} }, // FALSE           
    { {       276}, { 37} }, // IDENTIFIER      
    { {       281}, { 38} }, // NATURAL_LITERAL 
    { {       277}, { 39} }, // LEFT_PARENTHESIS
    { {       264}, { 40} }, // NOT             
    { {         0}, {  0} },                    
};

SR__ s_56[] =
{
    { { REQ_TOKEN}, {  8} },                    
    { {       308}, { 74} }, // expr            
    { {       262}, { 35} }, // TRUE            
    { {       263}, { 36} }, // FALSE           
    { {       276}, { 37} }, // IDENTIFIER      
    { {       281}, { 38} }, // NATURAL_LITERAL 
    { {       277}, { 39} }, // LEFT_PARENTHESIS
    { {       264}, { 40} }, // NOT             
    { {         0}, {  0} },                    
};

SR__ s_57[] =
{
    { { REQ_TOKEN}, {  8} },                    
    { {       308}, { 75} }, // expr            
    { {       262}, { 35} }, // TRUE            
    { {       263}, { 36} }, // FALSE           
    { {       276}, { 37} }, // IDENTIFIER      
    { {       281}, { 38} }, // NATURAL_LITERAL 
    { {       277}, { 39} }, // LEFT_PARENTHESIS
    { {       264}, { 40} }, // NOT             
    { {         0}, {  0} },                    
};

SR__ s_58[] =
{
    { { REQ_TOKEN}, { 12} },                     
    { {       278}, { 76} }, // RIGHT_PARENTHESIS
    { {       284}, { 48} }, // EQUAL            
    { {       282}, { 49} }, // AND              
    { {       283}, { 50} }, // OR               
    { {       285}, { 51} }, // LESS_THAN        
    { {       286}, { 52} }, // GREATER_THAN     
    { {       287}, { 53} }, // PLUS             
    { {       288}, { 54} }, // MINUS            
    { {       289}, { 55} }, // MULTIPLY         
    { {       290}, { 56} }, // DIV              
    { {       291}, { 57} }, // MOD              
    { {         0}, {  0} },                     
};

SR__ s_59[] =
{
    { { REQ_DEF}, {  11} },                
    { {     284}, {  48} }, // EQUAL       
    { {     282}, {  49} }, // AND         
    { {     283}, {  50} }, // OR          
    { {     285}, {  51} }, // LESS_THAN   
    { {     286}, {  52} }, // GREATER_THAN
    { {     287}, {  53} }, // PLUS        
    { {     288}, {  54} }, // MINUS       
    { {     289}, {  55} }, // MULTIPLY    
    { {     290}, {  56} }, // DIV         
    { {     291}, {  57} }, // MOD         
    { {       0}, { -32} },                
};

SR__ s_60[] =
{
    { { REQ_DEF}, {  14} },                  
    { {     309}, {  77} }, // if_second_half
    { {     299}, {  78} }, // expressions   
    { {     300}, {  16} }, // expression    
    { {     301}, {  17} }, // read          
    { {     302}, {  18} }, // write         
    { {     303}, {  19} }, // assignment    
    { {     304}, {  20} }, // while_loop    
    { {     305}, {  21} }, // if_statement  
    { {     274}, {  22} }, // READ          
    { {     275}, {  23} }, // WRITE         
    { {     276}, {  24} }, // IDENTIFIER    
    { {     271}, {  25} }, // WHILE         
    { {     266}, {  26} }, // IF            
    { {       0}, { -10} },                  
};

SR__ s_61[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -42} }, 
};

SR__ s_62[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       280}, { 79} }, // SEMICOLON
    { {         0}, {  0} },             
};

SR__ s_63[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       280}, { 80} }, // SEMICOLON
    { {         0}, {  0} },             
};

SR__ s_64[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -20} }, 
};

SR__ s_65[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       273}, { 81} }, // DONE
    { {         0}, {  0} },        
};

SR__ s_66[] =
{
    { { REQ_DEF}, {   8} },                
    { {     285}, {  51} }, // LESS_THAN   
    { {     286}, {  52} }, // GREATER_THAN
    { {     287}, {  53} }, // PLUS        
    { {     288}, {  54} }, // MINUS       
    { {     289}, {  55} }, // MULTIPLY    
    { {     290}, {  56} }, // DIV         
    { {     291}, {  57} }, // MOD         
    { {       0}, { -30} },                
};

SR__ s_67[] =
{
    { { REQ_DEF}, {   9} },                
    { {     284}, {  48} }, // EQUAL       
    { {     285}, {  51} }, // LESS_THAN   
    { {     286}, {  52} }, // GREATER_THAN
    { {     287}, {  53} }, // PLUS        
    { {     288}, {  54} }, // MINUS       
    { {     289}, {  55} }, // MULTIPLY    
    { {     290}, {  56} }, // DIV         
    { {     291}, {  57} }, // MOD         
    { {       0}, { -33} },                
};

SR__ s_68[] =
{
    { { REQ_DEF}, {   9} },                
    { {     284}, {  48} }, // EQUAL       
    { {     285}, {  51} }, // LESS_THAN   
    { {     286}, {  52} }, // GREATER_THAN
    { {     287}, {  53} }, // PLUS        
    { {     288}, {  54} }, // MINUS       
    { {     289}, {  55} }, // MULTIPLY    
    { {     290}, {  56} }, // DIV         
    { {     291}, {  57} }, // MOD         
    { {       0}, { -34} },                
};

SR__ s_69[] =
{
    { { REQ_DEF}, {   6} },            
    { {     287}, {  53} }, // PLUS    
    { {     288}, {  54} }, // MINUS   
    { {     289}, {  55} }, // MULTIPLY
    { {     290}, {  56} }, // DIV     
    { {     291}, {  57} }, // MOD     
    { {       0}, { -35} },            
};

SR__ s_70[] =
{
    { { REQ_DEF}, {   6} },            
    { {     287}, {  53} }, // PLUS    
    { {     288}, {  54} }, // MINUS   
    { {     289}, {  55} }, // MULTIPLY
    { {     290}, {  56} }, // DIV     
    { {     291}, {  57} }, // MOD     
    { {       0}, { -36} },            
};

SR__ s_71[] =
{
    { { REQ_DEF}, {   4} },            
    { {     289}, {  55} }, // MULTIPLY
    { {     290}, {  56} }, // DIV     
    { {     291}, {  57} }, // MOD     
    { {       0}, { -37} },            
};

SR__ s_72[] =
{
    { { REQ_DEF}, {   4} },            
    { {     289}, {  55} }, // MULTIPLY
    { {     290}, {  56} }, // DIV     
    { {     291}, {  57} }, // MOD     
    { {       0}, { -38} },            
};

SR__ s_73[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -39} }, 
};

SR__ s_74[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -40} }, 
};

SR__ s_75[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -41} }, 
};

SR__ s_76[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -31} }, 
};

SR__ s_77[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -22} }, 
};

SR__ s_78[] =
{
    { { REQ_TOKEN}, {  4} },          
    { {       270}, { 82} }, // ENDIF 
    { {       268}, { 83} }, // ELSE  
    { {       269}, { 84} }, // ELSEIF
    { {         0}, {  0} },          
};

SR__ s_79[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -18} }, 
};

SR__ s_80[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -19} }, 
};

SR__ s_81[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -21} }, 
};

SR__ s_82[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -23} }, 
};

SR__ s_83[] =
{
    { { REQ_DEF}, {  13} },                
    { {     299}, {  85} }, // expressions 
    { {     300}, {  16} }, // expression  
    { {     301}, {  17} }, // read        
    { {     302}, {  18} }, // write       
    { {     303}, {  19} }, // assignment  
    { {     304}, {  20} }, // while_loop  
    { {     305}, {  21} }, // if_statement
    { {     274}, {  22} }, // READ        
    { {     275}, {  23} }, // WRITE       
    { {     276}, {  24} }, // IDENTIFIER  
    { {     271}, {  25} }, // WHILE       
    { {     266}, {  26} }, // IF          
    { {       0}, { -10} },                
};

SR__ s_84[] =
{
    { { REQ_TOKEN}, {  8} },                    
    { {       308}, { 86} }, // expr            
    { {       262}, { 35} }, // TRUE            
    { {       263}, { 36} }, // FALSE           
    { {       276}, { 37} }, // IDENTIFIER      
    { {       281}, { 38} }, // NATURAL_LITERAL 
    { {       277}, { 39} }, // LEFT_PARENTHESIS
    { {       264}, { 40} }, // NOT             
    { {         0}, {  0} },                    
};

SR__ s_85[] =
{
    { { REQ_TOKEN}, {  2} },         
    { {       270}, { 87} }, // ENDIF
    { {         0}, {  0} },         
};

SR__ s_86[] =
{
    { { REQ_TOKEN}, { 12} },                
    { {       267}, { 88} }, // THEN        
    { {       284}, { 48} }, // EQUAL       
    { {       282}, { 49} }, // AND         
    { {       283}, { 50} }, // OR          
    { {       285}, { 51} }, // LESS_THAN   
    { {       286}, { 52} }, // GREATER_THAN
    { {       287}, { 53} }, // PLUS        
    { {       288}, { 54} }, // MINUS       
    { {       289}, { 55} }, // MULTIPLY    
    { {       290}, { 56} }, // DIV         
    { {       291}, { 57} }, // MOD         
    { {         0}, {  0} },                
};

SR__ s_87[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -24} }, 
};

SR__ s_88[] =
{
    { { REQ_DEF}, {  14} },                  
    { {     309}, {  89} }, // if_second_half
    { {     299}, {  78} }, // expressions   
    { {     300}, {  16} }, // expression    
    { {     301}, {  17} }, // read          
    { {     302}, {  18} }, // write         
    { {     303}, {  19} }, // assignment    
    { {     304}, {  20} }, // while_loop    
    { {     305}, {  21} }, // if_statement  
    { {     274}, {  22} }, // READ          
    { {     275}, {  23} }, // WRITE         
    { {     276}, {  24} }, // IDENTIFIER    
    { {     271}, {  25} }, // WHILE         
    { {     266}, {  26} }, // IF            
    { {       0}, { -10} },                  
};

SR__ s_89[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -25} }, 
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,  s_68,  s_69,
  s_70,  s_71,  s_72,  s_73,  s_74,  s_75,  s_76,  s_77,  s_78,  s_79,
  s_80,  s_81,  s_82,  s_83,  s_84,  s_85,  s_86,  s_87,  s_88,  s_89,
};

} // anonymous namespace ends




// If the parsing function call uses arguments, then provide an overloaded
// function.  The code below doesn't rely on parameters, so no arguments are
// required.  Furthermore, parse uses a function try block to allow us to do
// ACCEPT and ABORT from anywhere, even from within members called by actions,
// simply throwing the appropriate exceptions.

ParserBase::ParserBase()
:
    // $insert requiredtokens
    d_requiredTokens__(0),
    d_acceptedTokens__(d_requiredTokens__),
    d_token__(_UNDETERMINED_),
    d_nextToken__(_UNDETERMINED_)
{}


void ParserBase::setDebug(bool mode)
{
    d_actionCases__ = false;
    d_debug__ = mode;
}

void ParserBase::setDebug(DebugMode__ mode)
{
    d_actionCases__ = mode & ACTIONCASES;
    d_debug__ =       mode & ON;
}

void Parser::print__()
{
// $insert print
}

void ParserBase::clearin()
{
    d_token__ = d_nextToken__ = _UNDETERMINED_;
}

void ParserBase::push__(size_t state)
{
    size_t currentSize = d_stateStack__.size();
    if (static_cast<size_t>(d_stackIdx__ + 1) == currentSize)
    {
        size_t newSize = currentSize + STACK_EXPANSION__;
        d_stateStack__.resize(newSize);
        // $insert LTYPEresize
        d_locationStack__.resize(newSize);
        if (d_valueStack__.capacity() >= newSize)
            d_valueStack__.resize(newSize);
        else
        {
            std::vector<STYPE__> enlarged(newSize);
            for (size_t idx = 0; idx != currentSize; ++idx)
                enlarged[idx] = std::move(d_valueStack__[idx]);
            d_valueStack__.swap(enlarged);
        }
    }
    ++d_stackIdx__;
    d_stateStack__[d_stackIdx__] = d_state__ = state;
    // $insert LTYPEpush
    *(d_lsp__ = &d_locationStack__[d_stackIdx__]) = d_loc__;
    *(d_vsp__ = &d_valueStack__[d_stackIdx__]) = std::move(d_val__);
}

void ParserBase::popToken__()
{
    d_token__ = d_nextToken__;

    d_val__ = std::move(d_nextVal__);
    d_nextVal__ = STYPE__();

    d_nextToken__ = _UNDETERMINED_;
}
     
void ParserBase::pushToken__(int token)
{
    d_nextToken__ = d_token__;
    d_nextVal__ = std::move(d_val__);
    d_token__ = token;
}
     
void ParserBase::pop__(size_t count)
{
    if (d_stackIdx__ < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx__ -= count;
    d_state__ = d_stateStack__[d_stackIdx__];
    d_vsp__ = &d_valueStack__[d_stackIdx__];
    // $insert LTYPEpop
    d_lsp__ = &d_locationStack__[d_stackIdx__];
}

inline size_t ParserBase::top__() const
{
    return d_stateStack__[d_stackIdx__];
}

void Parser::executeAction(int production)
try
{
    if (d_token__ != _UNDETERMINED_)
        pushToken__(d_token__);     // save an already available token

    switch (production)
    {
        // $insert actioncases
        
        case 1:
#line 27 "lang.y"
        {
         std::cout << "start -> program" << std::endl;
         }
        break;

        case 2:
#line 33 "lang.y"
        {
         std::cout << "program -> header declarations body" << std::endl;
         }
        break;

        case 3:
#line 39 "lang.y"
        {
         std::cout << "header -> PROGRAM IDENTIFIER" << std::endl;
         }
        break;

        case 4:
#line 45 "lang.y"
        {
         std::cout << "declarations -> \"\"" << std::endl;
         }
        break;

        case 5:
#line 50 "lang.y"
        {
         std::cout << "declarations -> declaration declarations" << std::endl;
         }
        break;

        case 6:
#line 56 "lang.y"
        {
         std::cout << "declaration -> type IDENTIFIER SEMICOLON" << std::endl;
         }
        break;

        case 7:
#line 63 "lang.y"
        {
         std::cout << "type -> NATURAL" << std::endl;
         }
        break;

        case 8:
#line 68 "lang.y"
        {
         std::cout << "type -> BOOLEAN" << std::endl;
         }
        break;

        case 9:
#line 74 "lang.y"
        {
         std::cout << "body -> BEGIN statements END" << std::endl;
         }
        break;

        case 10:
#line 80 "lang.y"
        {
         std::cout << "expressions -> \"\"" << std::endl;
         }
        break;

        case 11:
#line 85 "lang.y"
        {
         std::cout << "expressions -> expression expressions" << std::endl;
         }
        break;

        case 12:
#line 92 "lang.y"
        {
         std::cout << "expression -> read" << std::endl;
         }
        break;

        case 13:
#line 97 "lang.y"
        {
         std::cout << "expression -> write" << std::endl;
         }
        break;

        case 14:
#line 102 "lang.y"
        {
         std::cout << "expression -> assignment" << std::endl;
         }
        break;

        case 15:
#line 107 "lang.y"
        {
         std::cout << "expression -> while_loop" << std::endl;
         }
        break;

        case 16:
#line 116 "lang.y"
        {
         std::cout << "expression -> skip" << std::endl;
         }
        break;

        case 17:
#line 112 "lang.y"
        {
         std::cout << "expression -> if_statement" << std::endl;
         }
        break;

        case 18:
#line 122 "lang.y"
        {
         std::cout << "read -> READ LEFT_PARENTHESIS IDENTIFIER RIGHT_PARENTHESIS SEMICOLON" << std::endl;
         }
        break;

        case 19:
#line 128 "lang.y"
        {
         std::cout << "write -> WRITE LEFT_PARENTHESIS expr RIGHT_PARENTHESIS SEMICOLON" << std::endl;
         }
        break;

        case 20:
#line 134 "lang.y"
        {
         std::cout << "assignment -> IDENTIFIER ASSIGN expr SEMICOLON" << std::endl;
         }
        break;

        case 21:
#line 140 "lang.y"
        {
         std::cout << "while_loop -> WHILE expr DO expressions DONE" << std::endl;
         }
        break;

        case 22:
#line 146 "lang.y"
        {
         std::cout << "if_statement -> IF expr THEN if_second_half" << std::endl;
         }
        break;

        case 23:
#line 153 "lang.y"
        {
         std::cout << "if_second_half -> expressions ENDIF" << std::endl;
         }
        break;

        case 24:
#line 158 "lang.y"
        {
         std::cout << "if_second_half -> expressions ELSE expressions ENDIF" << std::endl;
         }
        break;

        case 25:
#line 163 "lang.y"
        {
         std::cout << "if_second_half -> expressions ELSEIF expr THEN if_second_half" << std::endl;
         }
        break;

        case 26:
#line 170 "lang.y"
        {
         std::cout << "expr -> TRUE" << std::endl;
         }
        break;

        case 27:
#line 175 "lang.y"
        {
         std::cout << "expr -> FALSE" << std::endl;
         }
        break;

        case 28:
#line 180 "lang.y"
        {
         std::cout << "expr -> IDENTIFIER" << std::endl;
         }
        break;

        case 29:
#line 185 "lang.y"
        {
         std::cout << "expr -> NATURAL_LITERAL" << std::endl;
         }
        break;

        case 30:
#line 190 "lang.y"
        {
         std::cout << "expr -> expr EQUAL expr" << std::endl;
         }
        break;

        case 31:
#line 195 "lang.y"
        {
         std::cout << "expr -> LEFT_PARENTHESIS expr RIGHT_PARENTHESIS" << std::endl;
         }
        break;

        case 32:
#line 200 "lang.y"
        {
         std::cout << "expr -> NOT expr" << std::endl;
         }
        break;

        case 33:
#line 205 "lang.y"
        {
         std::cout << "expr -> expr AND expr" << std::endl;
         }
        break;

        case 34:
#line 210 "lang.y"
        {
         std::cout << "expr -> expr OR expr" << std::endl;
         }
        break;

        case 35:
#line 215 "lang.y"
        {
         std::cout << "expr -> expr LESS_THAN expr" << std::endl;
         }
        break;

        case 36:
#line 220 "lang.y"
        {
         std::cout << "expr -> expr GREATER_THAN expr" << std::endl;
         }
        break;

        case 37:
#line 225 "lang.y"
        {
         std::cout << "expr -> expr PLUS expr" << std::endl;
         }
        break;

        case 38:
#line 230 "lang.y"
        {
         std::cout << "expr -> expr MINUS expr" << std::endl;
         }
        break;

        case 39:
#line 235 "lang.y"
        {
         std::cout << "expr -> expr MULTIPLY expr" << std::endl;
         }
        break;

        case 40:
#line 240 "lang.y"
        {
         std::cout << "expr -> expr DIV expr" << std::endl;
         }
        break;

        case 41:
#line 245 "lang.y"
        {
         std::cout << "expr -> expr MOD expr" << std::endl;
         }
        break;

        case 42:
#line 251 "lang.y"
        {
         std::cout << "skip -> SKIP SEMICOLON" << std::endl;
         }
        break;

    }
}
catch (std::exception const &exc)
{
    exceptionHandler__(exc);
}

inline void ParserBase::reduce__(PI__ const &pi)
{
    d_token__ = pi.d_nonTerm;
    pop__(pi.d_size);

}

// If d_token__ is _UNDETERMINED_ then if d_nextToken__ is _UNDETERMINED_ another
// token is obtained from lex(). Then d_nextToken__ is assigned to d_token__.
void Parser::nextToken()
{
    if (d_token__ != _UNDETERMINED_)        // no need for a token: got one
        return;                             // already

    if (d_nextToken__ != _UNDETERMINED_)
    {
        popToken__();                       // consume pending token
    }
    else
    {
        ++d_acceptedTokens__;               // accept another token (see
                                            // errorRecover())
        d_token__ = lex();
        if (d_token__ <= 0)
            d_token__ = _EOF_;
    }
    print();
}

// if the final transition is negative, then we should reduce by the rule
// given by its positive value. Note that the `recovery' parameter is only
// used with the --debug option
int Parser::lookup(bool recovery)
{
// $insert threading
    SR__ *sr = s_state[d_state__];          // get the appropriate state-table
    int lastIdx = sr->d_lastIdx;            // sentinel-index in the SR__ array
    
    SR__ *lastElementPtr = sr + lastIdx;
    lastElementPtr->d_token = d_token__;    // set search-token
    
    SR__ *elementPtr = sr + 1;              // start the search at s_xx[1]
    while (elementPtr->d_token != d_token__)
        ++elementPtr;
    

    if (elementPtr == lastElementPtr)   // reached the last element
    {
        if (elementPtr->d_action < 0)   // default reduction
        {
            return elementPtr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = elementPtr->d_action;


    return action;
}

    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)
void Parser::errorRecovery()
try
{
    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error("Syntax error");                  // simply skip input

    }


    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        pop__();
    }

    // In the error state, lookup a token allowing us to proceed.
    // Continuation may be possible following multiple reductions,
    // but eventuall a shift will be used, requiring the retrieval of
    // a terminal token. If a retrieved token doesn't match, the catch below 
    // will ensure the next token is requested in the while(true) block
    // implemented below:

    int lastToken = d_token__;                  // give the unexpected token a
                                                // chance to be processed
                                                // again.

    pushToken__(_error_);                       // specify _error_ as next token
    push__(lookup(true));                       // push the error state

    d_token__ = lastToken;                      // reactivate the unexpected
                                                // token (we're now in an
                                                // ERROR state).

    bool gotToken = true;                       // the next token is a terminal

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
            {
                gotToken = d_token__ == _UNDETERMINED_;
                nextToken();                    // obtain next token
            }
            
            int action = lookup(true);

            if (action > 0)                 // push a new state
            {
                push__(action);
                popToken__();

                if (gotToken)
                {

                    d_acceptedTokens__ = 0;
                    return;
                }
            }
            else if (action < 0)
            {
                // no actions executed on recovery but save an already 
                // available token:
                if (d_token__ != _UNDETERMINED_)
                    pushToken__(d_token__);
 
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else
                ABORT();                    // abort when accepting during
                                            // error recovery
        }
        catch (...)
        {
            if (d_token__ == _EOF_)
                ABORT();                    // saw inappropriate _EOF_
                      
            popToken__();                   // failing token now skipped
        }
    }
}
catch (ErrorRecovery__)       // This is: DEFAULT_RECOVERY_MODE
{
    ABORT();
}

    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and d_token__ as well as
    // d_nextToken__ are initialized to _UNDETERMINED_. 
    //
    // Then, in an eternal loop:
    //
    //  1. If a state does not have REQ_TOKEN no token is assigned to
    //     d_token__. If the state has REQ_TOKEN, nextToken() is called to
    //      determine d_nextToken__ and d_token__ is set to
    //     d_nextToken__. nextToken() will not call lex() unless d_nextToken__ is 
    //     _UNDETERMINED_. 
    //
    //  2. lookup() is called: 
    //     d_token__ is stored in the final element's d_token field of the
    //     state's SR_ array. 
    //
    //  3. The current token is looked up in the state's SR_ array
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token__ is not found, and the state has no
    //     default reduction. Error handling was described at the top of this
    //     file.

int Parser::parse()
try 
{
    push__(0);                              // initial state
    clearin();                              // clear the tokens.

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
                nextToken();                // obtain next token


            int action = lookup(false);     // lookup d_token__ in d_state__

            if (action > 0)                 // SHIFT: push a new state
            {
                push__(action);
                popToken__();               // token processed
            }
            else if (action < 0)            // REDUCE: execute and pop.
            {
                executeAction(-action);
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else 
                ACCEPT();
        }
        catch (ErrorRecovery__)
        {
            errorRecovery();
        }
    }
}
catch (Return__ retValue)
{
    return retValue;
}



